# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jorge Barrasa-Fano
tagline:          'Personal Site'
description:      ''
url:              https://jorgebarrasafano.github.io/

highlighter:      rouge
markdown:         kramdown

paginate:         5

github:
  repo:           https://github.com/JorgeBarrasaFano/jorgebarrasafano.github.io
